In [2]:
import feather
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
walmart_df = feather.read_dataframe('Datos/base_nuevas_vars/walmart.feather')
nrow=walmart_df['TripType'].count()
walmart_df_Y=walmart_df['TripType']
walmart_df=walmart_df.drop(['VisitNumber', 'TripType'], axis=1)

In [4]:
df_Weekday = pd.get_dummies(walmart_df['Weekday'])

In [5]:
walmart_df = pd.concat([walmart_df, df_Weekday], axis=1)
walmart_df = walmart_df.drop('Weekday', axis=1)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(walmart_df, walmart_df_Y, random_state=0, stratify=walmart_df_Y)

In [13]:
X_test[:5].values

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  4.,  0.,  9.,  4.,  4.,  0.,  0.,  0.,  1.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         0.,  0.,  0.,  3.,  1., 17.,  3.,  4.,  1.,  0.,  0.,  0.,  1.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
   

In [14]:
import pickle
with open("model3.pkl", "rb") as f:
     model_loaded = pickle.load(f)

In [15]:
model_loaded.best_score_

-1.052927519021338

In [18]:
pred_reg = model_loaded.predict(X_test)

In [28]:
len(pred_reg)

23919

In [19]:
pred_reg

array([39,  9,  6, ..., 39, 40,  5], dtype=int32)

In [20]:
print(pred_reg)

[39  9  6 ... 39 40  5]


In [21]:
model_loaded.predict_proba(X_test)

array([[9.58692270e-04, 4.26837390e-03, 8.44824629e-03, ...,
        1.31117200e-02, 3.88964854e-03, 3.21923795e-02],
       [4.62379097e-03, 2.44145027e-03, 4.74846257e-03, ...,
        1.65196398e-02, 3.21860365e-03, 2.03483556e-01],
       [1.78587260e-03, 3.53462683e-03, 1.24244814e-02, ...,
        4.99987030e-03, 1.87455587e-03, 1.35588118e-02],
       ...,
       [6.01577215e-04, 1.02486517e-03, 3.46843166e-03, ...,
        8.24119728e-02, 1.97188865e-02, 4.12208292e-03],
       [8.78752776e-07, 9.05499068e-07, 4.34409069e-06, ...,
        8.14966539e-06, 9.75667935e-05, 2.56646475e-06],
       [1.01056775e-04, 3.64028666e-02, 7.52025179e-01, ...,
        2.51333740e-03, 1.12628625e-03, 1.42201517e-03]])

In [29]:
from sklearn.metrics import log_loss
log_loss(y_test, pred_reg)

ValueError: y_true and y_pred contain different number of classes 38, 2. Please provide the true labels explicitly through the labels argument. Classes found in y_true: [  3   4   5   6   7   8   9  12  14  15  18  19  20  21  22  23  24  25
  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43
  44 999]

In [22]:
dffull = feather.read_dataframe('Datos/base_nuevas_vars/walmart.feather')

In [24]:
dffull

VisitNumber  TripType Weekday  1-HR PHOTO  ACCESSORIES  AUTOMOTIVE  \
0                5       999  Friday         0.0          0.0         0.0   
1                7        30  Friday         0.0          0.0         0.0   
2                8        26  Friday         0.0          0.0         0.0   
3                9         8  Friday         0.0          0.0         0.0   
4               10         8  Friday         0.0          0.0         0.0   
5               11        35  Friday         0.0          0.0         0.0   
6               12        41  Friday         0.0          0.0         0.0   
7               15        21  Friday         0.0          0.0         0.0   
8               17         6  Friday         0.0          0.0         0.0   
9               19        42  Friday         0.0          1.0         0.0   
10              20         7  Friday         0.0          0.0         0.0   
11              23         9  Friday         0.0          0.0         0.0   
12              25         8  Friday         0.0          0.0         0.0   
13              26        39  Friday         0.0          0.0         0.0   
14              28        25  Friday         0.0          0.0         0.0   
15              29         8  Friday         0.0          0.0         0.0   
16              30         9  Friday         0.0          0.0         0.0   
17              31         8  Friday         0.0          0.0         0.0   
18              32         8  Friday         0.0          0.0         0.0   
19              33         8  Friday         0.0          0.0         0.0   
20              40         8  Friday         0.0          0.0         0.0   
21              41         8  Friday         0.0          0.0         0.0   
22              42         8  Friday         0.0          0.0         0.0   
23              43        38  Friday         0.0          0.0         0.0   
24              45         8  Friday         0.0          0.0         0.0   
25              47        35  Friday         0.0          0.0         0.0   
26              49        15  Friday         0.0          0.0         0.0   
27              50         9  Friday         0.0          0.0         0.0   
28              51         8  Friday         0.0          0.0         0.0   
29              53         8  Friday         0.0          0.0         0.0   
...            ...       ...     ...         ...          ...         ...   
95644       191276        21  Sunday         0.0          0.0         0.0   
95645       191277        44  Sunday         0.0          0.0         0.0   
95646       191280         8  Sunday         0.0          0.0         0.0   
95647       191283        44  Sunday         0.0          0.0         0.0   
95648       191286        40  Sunday         0.0          0.0         0.0   
95649       191287        26  Sunday         0.0          0.0         0.0   
95650       191289         8  Sunday         0.0          0.0         0.0   
95651       191291         8  Sunday         0.0          0.0         0.0   
95652       191293        36  Sunday         0.0          0.0         0.0   
95653       191298        40  Sunday         0.0          0.0         1.0   
95654       191301        42  Sunday         0.0          0.0         0.0   
95655       191304        36  Sunday         0.0          0.0         0.0   
95656       191305        31  Sunday         0.0          0.0         0.0   
95657       191311         9  Sunday         0.0          0.0         0.0   
95658       191312        42  Sunday         0.0          0.0         0.0   
95659       191313        30  Sunday         0.0          0.0         0.0   
95660       191318         7  Sunday         0.0          0.0         0.0   
95661       191322        38  Sunday         0.0          0.0         0.0   
95662       191324        40  Sunday         0.0          0.0         3.0   
95663       191326        38  Sunday         0.0          0.0         0.0   
956